### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by xethorn** [eleme/meepo#29]
First: thanks. This library is awesome :) I've been trying to use meepo for already a day (using the `mysql_pub` as a daemon) but I'm unfortunately not able to get it to work. 

Here are the steps:
1. Launch a ec2 instance on amazon.
2. Install mysql. 
3. Log into mysql, create a database named `db` and a table named `test`.
4. Update my.cnf to add: `server-id`, `log_bin`, and `binlog_do_db` (points to a db named db).
5. Restart mysql.
6. Install meepo

In two different terminals:

Launch meepo.py:

``` python
from meepo.pub import mysql_pub
from blinker import signal

sg = signal('test_write')

@sg.connect
def on_write(pk):
    print(pk)

mysql_pub('mysql://root@localhost/db', blocking=True)
```

And in the other terminal, just add new values onto the test table. Nothing is printed. Any idea?

**Comment by lxyu** [comment]
Did you enable the row-based binlog in mysql? something like `binlog_format = 'ROW'`, refer to this link: http://dev.mysql.com/doc/refman/5.1/en/binary-log-setting.html

**Comment by mortaliorchard** [comment]
Yes – that was it! I'll try to find some time to update the doc.

**Comment by xethorn** [comment]
Yes - that was it! Will try to find some time to update the doc. Many thanks.
